## ref: https://github.com/helmfile/helmfile

## helm repositories
repositories:
  - name: baseCharts
    url: https://juriku.github.io/helm-charts
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io
  - name: incubator
    url:  https://charts.helm.sh/incubator


## helm default settings
helmDefaults:
  wait: true
  force: false
  timeout: 360
  historyMax: 10

missingFileHandler: Error


## templates and yaml anchors
templates:

  ## full values anchors
  valuesOnly: &default-values
    values:
      - ../helm/values/{{`{{ .Release.Name }}`}}/defaults.yaml.gotmpl


## environment states
environments:
  default:


## defining all releases
releases:

  ## nginx-ingress
  - name: nginx-ingress
    chart: ingress-nginx/ingress-nginx
    version: 3.40.0
    wait: true
    <<: *default-values

  ## cert manager for Let's Encrypt
  - name: cert-manager
    chart: jetstack/cert-manager
    version: v1.7.1
    wait: true
    namespace: cert-manager
    <<: *default-values

  ## app-test
  - name: app-test
    namespace: default
    chart: baseCharts/app
    version: 0.6.11
    <<: *default-values

  ## ingress-test
  - name: ingress-test
    namespace: default
    chart: baseCharts/ingress
    version: 0.6.3
    <<: *default-values

  ## letsencrypt-http
  - name: letsencrypt-http
    namespace: cert-manager
    chart: incubator/raw
    version: 0.2.4
    values:
    - resources:
      - apiVersion: cert-manager.io/v1
        kind: ClusterIssuer
        metadata:
          name: letsencrypt-http
        spec:
          acme:
            email: test@{{ requiredEnv "DNS_HOST_NAME" }}
            privateKeySecretRef:
              name: letsencrypt-http
            server: https://acme-v02.api.letsencrypt.org/directory
            solvers:
            - http01:
                ingress:
                  class: nginx
